//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""41f23846-2563-4de0-a75a-592bf53314fb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5956968f-f3a9-4041-bc6e-4e648d88d1ee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""ecdbada3-5ba8-4752-88e7-7f85bcf8e6e8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""8f03b33c-0769-4fd5-8d5f-4fae4bb31e3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""50afd23c-f8e8-4bc2-b62b-615ea1b157ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventorySlotOne"",
                    ""type"": ""Button"",
                    ""id"": ""5131bbc0-420f-41c7-905d-d3d416f63a63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventorySlotThree"",
                    ""type"": ""Button"",
                    ""id"": ""c1ff334b-9020-44fe-8980-cd1515104f89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventorySlotTwo"",
                    ""type"": ""Button"",
                    ""id"": ""76e250e7-8bc2-45e7-9918-ea77ad7f02c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""157ca4fb-20b2-492a-9bf9-85c78f4b5c1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backpack"",
                    ""type"": ""Button"",
                    ""id"": ""ba55d49b-f3a0-4c6e-a952-673d2c487997"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FallOut"",
                    ""type"": ""Button"",
                    ""id"": ""6ec3eb76-98c8-48b4-8948-b37e6d6424e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressZ"",
                    ""type"": ""Button"",
                    ""id"": ""cf7e19a7-3a0d-4287-aee6-6ce6fa0c2e4b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressX"",
                    ""type"": ""Button"",
                    ""id"": ""04480096-793b-484d-9e8e-3431f48d62ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressC"",
                    ""type"": ""Button"",
                    ""id"": ""6b74cccc-a107-4175-814a-a05fb0ab8b05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressB"",
                    ""type"": ""Button"",
                    ""id"": ""bbc751f0-ec0d-4d1b-9f08-d2973e34446b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressN"",
                    ""type"": ""Button"",
                    ""id"": ""5b459df4-ade2-471c-b3ec-87f0a2ee7225"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressM"",
                    ""type"": ""Button"",
                    ""id"": ""60701418-b76a-4fd7-9edf-d2c1f208c3f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""cfd72fc4-7e21-4927-bea6-282ce27bf0ff"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0bdf498b-b424-40ff-8fb5-eb945307a901"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""76393dab-0ffb-401a-8200-7b7ee15d17f2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""38cdab16-af62-4d74-888b-41cd5d747951"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e0dbc6d9-83c1-44c3-96a5-e9174087cf96"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bc4b7867-db29-46ca-ad79-abc8944d9e25"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""601046fe-156d-4288-8cd8-b8f1a660c75c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e9868278-8f0c-49a3-a83b-b2525fdb1e64"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1e74e76e-b693-4747-9882-e13eee3544cc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e598f61a-9ca5-4cd5-a8a1-55bfc93e34de"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0682e8ed-7e43-4e2a-b508-fd15de26fb82"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6852a5a-4851-4c7c-80ea-5b637c709d54"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a8988b9-2129-459e-9785-8735eb36d1c7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf0b271b-b7dd-4a5d-ba26-8a83122106f7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySlotOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7c460c8-8cfb-443c-a0f7-9fabedd604ed"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySlotThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1204757e-6abd-48d3-99ce-3b04abb1e77b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySlotTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02ded343-dc65-451a-a8c4-1e78bac85aec"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66e6d00d-be56-43c8-8102-0a07229e4675"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backpack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29ef715a-2049-4c0d-9fc0-f715b28d35a3"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FallOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d890f8ae-c32f-48c2-9978-71e9f4f98df8"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de45706d-7d07-4774-8f2a-6f1670c936ac"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf1e7dba-6094-416c-b218-8be0bc75b744"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4aedbd29-2da6-414c-989a-2d8ac369e399"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8fed49-19d9-4c07-b19c-74e74db55cd9"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b61251fb-a691-4d69-b63a-5364cabacb94"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_InventorySlotOne = m_Player.FindAction("InventorySlotOne", throwIfNotFound: true);
        m_Player_InventorySlotThree = m_Player.FindAction("InventorySlotThree", throwIfNotFound: true);
        m_Player_InventorySlotTwo = m_Player.FindAction("InventorySlotTwo", throwIfNotFound: true);
        m_Player_Click = m_Player.FindAction("Click", throwIfNotFound: true);
        m_Player_Backpack = m_Player.FindAction("Backpack", throwIfNotFound: true);
        m_Player_FallOut = m_Player.FindAction("FallOut", throwIfNotFound: true);
        m_Player_PressZ = m_Player.FindAction("PressZ", throwIfNotFound: true);
        m_Player_PressX = m_Player.FindAction("PressX", throwIfNotFound: true);
        m_Player_PressC = m_Player.FindAction("PressC", throwIfNotFound: true);
        m_Player_PressB = m_Player.FindAction("PressB", throwIfNotFound: true);
        m_Player_PressN = m_Player.FindAction("PressN", throwIfNotFound: true);
        m_Player_PressM = m_Player.FindAction("PressM", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_InventorySlotOne;
    private readonly InputAction m_Player_InventorySlotThree;
    private readonly InputAction m_Player_InventorySlotTwo;
    private readonly InputAction m_Player_Click;
    private readonly InputAction m_Player_Backpack;
    private readonly InputAction m_Player_FallOut;
    private readonly InputAction m_Player_PressZ;
    private readonly InputAction m_Player_PressX;
    private readonly InputAction m_Player_PressC;
    private readonly InputAction m_Player_PressB;
    private readonly InputAction m_Player_PressN;
    private readonly InputAction m_Player_PressM;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @InventorySlotOne => m_Wrapper.m_Player_InventorySlotOne;
        public InputAction @InventorySlotThree => m_Wrapper.m_Player_InventorySlotThree;
        public InputAction @InventorySlotTwo => m_Wrapper.m_Player_InventorySlotTwo;
        public InputAction @Click => m_Wrapper.m_Player_Click;
        public InputAction @Backpack => m_Wrapper.m_Player_Backpack;
        public InputAction @FallOut => m_Wrapper.m_Player_FallOut;
        public InputAction @PressZ => m_Wrapper.m_Player_PressZ;
        public InputAction @PressX => m_Wrapper.m_Player_PressX;
        public InputAction @PressC => m_Wrapper.m_Player_PressC;
        public InputAction @PressB => m_Wrapper.m_Player_PressB;
        public InputAction @PressN => m_Wrapper.m_Player_PressN;
        public InputAction @PressM => m_Wrapper.m_Player_PressM;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @InventorySlotOne.started += instance.OnInventorySlotOne;
            @InventorySlotOne.performed += instance.OnInventorySlotOne;
            @InventorySlotOne.canceled += instance.OnInventorySlotOne;
            @InventorySlotThree.started += instance.OnInventorySlotThree;
            @InventorySlotThree.performed += instance.OnInventorySlotThree;
            @InventorySlotThree.canceled += instance.OnInventorySlotThree;
            @InventorySlotTwo.started += instance.OnInventorySlotTwo;
            @InventorySlotTwo.performed += instance.OnInventorySlotTwo;
            @InventorySlotTwo.canceled += instance.OnInventorySlotTwo;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @Backpack.started += instance.OnBackpack;
            @Backpack.performed += instance.OnBackpack;
            @Backpack.canceled += instance.OnBackpack;
            @FallOut.started += instance.OnFallOut;
            @FallOut.performed += instance.OnFallOut;
            @FallOut.canceled += instance.OnFallOut;
            @PressZ.started += instance.OnPressZ;
            @PressZ.performed += instance.OnPressZ;
            @PressZ.canceled += instance.OnPressZ;
            @PressX.started += instance.OnPressX;
            @PressX.performed += instance.OnPressX;
            @PressX.canceled += instance.OnPressX;
            @PressC.started += instance.OnPressC;
            @PressC.performed += instance.OnPressC;
            @PressC.canceled += instance.OnPressC;
            @PressB.started += instance.OnPressB;
            @PressB.performed += instance.OnPressB;
            @PressB.canceled += instance.OnPressB;
            @PressN.started += instance.OnPressN;
            @PressN.performed += instance.OnPressN;
            @PressN.canceled += instance.OnPressN;
            @PressM.started += instance.OnPressM;
            @PressM.performed += instance.OnPressM;
            @PressM.canceled += instance.OnPressM;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @InventorySlotOne.started -= instance.OnInventorySlotOne;
            @InventorySlotOne.performed -= instance.OnInventorySlotOne;
            @InventorySlotOne.canceled -= instance.OnInventorySlotOne;
            @InventorySlotThree.started -= instance.OnInventorySlotThree;
            @InventorySlotThree.performed -= instance.OnInventorySlotThree;
            @InventorySlotThree.canceled -= instance.OnInventorySlotThree;
            @InventorySlotTwo.started -= instance.OnInventorySlotTwo;
            @InventorySlotTwo.performed -= instance.OnInventorySlotTwo;
            @InventorySlotTwo.canceled -= instance.OnInventorySlotTwo;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @Backpack.started -= instance.OnBackpack;
            @Backpack.performed -= instance.OnBackpack;
            @Backpack.canceled -= instance.OnBackpack;
            @FallOut.started -= instance.OnFallOut;
            @FallOut.performed -= instance.OnFallOut;
            @FallOut.canceled -= instance.OnFallOut;
            @PressZ.started -= instance.OnPressZ;
            @PressZ.performed -= instance.OnPressZ;
            @PressZ.canceled -= instance.OnPressZ;
            @PressX.started -= instance.OnPressX;
            @PressX.performed -= instance.OnPressX;
            @PressX.canceled -= instance.OnPressX;
            @PressC.started -= instance.OnPressC;
            @PressC.performed -= instance.OnPressC;
            @PressC.canceled -= instance.OnPressC;
            @PressB.started -= instance.OnPressB;
            @PressB.performed -= instance.OnPressB;
            @PressB.canceled -= instance.OnPressB;
            @PressN.started -= instance.OnPressN;
            @PressN.performed -= instance.OnPressN;
            @PressN.canceled -= instance.OnPressN;
            @PressM.started -= instance.OnPressM;
            @PressM.performed -= instance.OnPressM;
            @PressM.canceled -= instance.OnPressM;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnInventorySlotOne(InputAction.CallbackContext context);
        void OnInventorySlotThree(InputAction.CallbackContext context);
        void OnInventorySlotTwo(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnBackpack(InputAction.CallbackContext context);
        void OnFallOut(InputAction.CallbackContext context);
        void OnPressZ(InputAction.CallbackContext context);
        void OnPressX(InputAction.CallbackContext context);
        void OnPressC(InputAction.CallbackContext context);
        void OnPressB(InputAction.CallbackContext context);
        void OnPressN(InputAction.CallbackContext context);
        void OnPressM(InputAction.CallbackContext context);
    }
}
